number: null
at: 2020-02-18T16:01:49.916Z
by: Patrick Kettner
environment: local
commit:
  sha: 2d8d5869e
  message: "guidelines for creating a successful story narrative and technical resources  (#3479)\n\n* initial push\r\n\r\n* small fix\r\n\r\n* small fixes\r\n\r\n* fixed links and such\r\n\r\n* fixed link!"
